### PR TITLE
Support skipping a specific source from resolving

### PR DESCRIPTION
**Pull request by nulls**

### CODE REVIEW

**Comment by Eskibear** [comment]
Thanks for the contribution! Overall it looks good. 

One more thing to discuss, for me it looks too many `skipXXX` properties in options, which will make other properties not easily found in suggestion candidates when writing code. I myself perfer:
```
Options: {
    ...
    skipFrom: {
        jabba?: boolean;
       asdf?:boolean;
       ...
    }

}
```

And you check `options?.skipFrom?.xxxx`. WDYT?

**Comment by nulls** [comment]
> And you check `options?.skipFrom?.xxxx`. WDYT?

Agree, will change now

**Review by nulls — COMMENTED** [review]
combined all skipFrom* to a single object

**Review by Eskibear — APPROVED** [review]
Thanks!

**Pull request merged**
