### PR TITLE
Support Java runtimes from PATH which doesn't fit to `looksLikeJavaHome`

### PR DESCRIPTION
**Pull request by nulls**

### CODE REVIEW

**Comment by Eskibear** [comment]
Two concerns:
- i) if multiple runtimes (not "looks like" java home) specified in PATH, e.g. `PATH=path-to-jdk-a;path-to-jdk-b;` This approach will only recognize jdk-a. 
- ii) executing `java` command is expensive as it launchs jvm.

One approach is to iterate every entry in PATH, if `bin/java` exists, mark it as a Java home directory. It would avoid to launch JVM but only filesystem io cost.

Another thing I've been thinking is, provide options to specify whether to search each source for java home directories. E.g. 
```
type Options = {
checkJAVAHOME: boolean
checkSDKMan: boolean
checkPATH: boolean
...
}
```
Make cheap ones default to true, and expensive ones default to false. Then the new changes won't affect other users, and it also unblock you perform a more aggressive search with more candidates.

WDYT?

**Review by 0x6675636b796f75676974687562 — APPROVED** [review]

**Review by adjtime — APPROVED** [review]

**Review by unix-junkie — APPROVED** [review]

**Comment by nulls** [comment]
> Two concerns:
> 
> * i) if multiple runtimes (not "looks like" java home) specified in PATH, e.g. `PATH=path-to-jdk-a;path-to-jdk-b;` This approach will only recognize jdk-a.
> * ii) executing `java` command is expensive as it launchs jvm.
> 
> One approach is to iterate every entry in PATH, if `bin/java` exists, mark it as a Java home directory. It would avoid to launch JVM but only filesystem io cost.
> 
> Another thing I've been thinking is, provide options to specify whether to search each source for java home directories. E.g.
> 
> ```
> type Options = {
> checkJAVAHOME: boolean
> checkSDKMan: boolean
> checkPATH: boolean
> ...
> }
> ```
> 
> Make cheap ones default to true, and expensive ones default to false. Then the new changes won't affect other users, and it also unblock you perform a more aggressive search with more candidates.
> 
> WDYT?

Agree with both concerns, but the second one is out of scope of this PR.

Will change the current PR to checking `bin/java` and create a new one with flags for sources later

**Comment by 0x6675636b796f75676974687562** [comment]
@nulls I suggest you also add `-XX:+IgnoreUnrecognizedVMOptions` when launching a JVM.

This way, it'll work even with Java 6.

**Comment by nulls** [comment]
> @nulls I suggest you also add `-XX:+IgnoreUnrecognizedVMOptions` when launching a JVM.
> 
> This way, it'll work even with Java 6.

thanks, but I avoided running `java` to detect `java.home` as suggested @Eskibear

**Comment by nulls** [comment]
@Eskibear 

> > Two concerns:
> > 
> > * i) if multiple runtimes (not "looks like" java home) specified in PATH, e.g. `PATH=path-to-jdk-a;path-to-jdk-b;` This approach will only recognize jdk-a.
> > * ii) executing `java` command is expensive as it launchs jvm.
> > 
> > One approach is to iterate every entry in PATH, if `bin/java` exists, mark it as a Java home directory. It would avoid to launch JVM but only filesystem io cost.
> > Another thing I've been thinking is, provide options to specify whether to search each source for java home directories. E.g.
> > ```
> > type Options = {
> > checkJAVAHOME: boolean
> > checkSDKMan: boolean
> > checkPATH: boolean
> > ...
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Make cheap ones default to true, and expensive ones default to false. Then the new changes won't affect other users, and it also unblock you perform a more aggressive search with more candidates.
> > WDYT?
> 
> Agree with both concerns, but the second one is out of scope of this PR.
> 
> Will change the current PR to checking `bin/java` and create a new one with flags for sources later

@Eskibear,
Updated the PR to check additionally `JAVA_FILENAME` in entries from `PATH`.

And created https://github.com/Eskibear/node-jdk-utils/pull/14 for the second suggestion

**Pull request merged**
